### PR TITLE
Added Support for Partials

### PR DESCRIPTION
**Pull request by MadLittleMods**
Adds support for partials (for non-built require projects). 

My use case is NOT building my require setup so I am unsure how to code for it exactly.

### CODE REVIEW

**Comment by guybedford** [comment]
This looks great. The build really isn't tricky at all from that either, so I'm happy to look into this.

Do you think it would be possible to get a little test going? Just a running example that can work when opening the html page would be great to have there for future changes (otherwise I have no reference point for updates).

**Comment by MadLittleMods** [comment]
I removed the old test and added my new test that demonstrates the partials, helpers, and a normal template. I even added an example of how to use a partial to dynamically add content.

I removed the handlebars assets from the main directory and moved them to the `hbs-test` directory. The only thing not encapsulated in the test directory is the `hbs.js` plugin itself which is referenced relatively.

_Of course it can't be run in the `file://` protocol as the whole cross-domain hoo-ha. But this is a problem with any requirejs project_

**Comment by guybedford** [comment]
Just to update on this - unfortunately I'm not going to have time for a proper review until later this month (around the 20th or so). I'd rather do it right than push this through, especially since maintaining this means bringing it from an unsupported module to something more supported. Thanks for your patience.

**Comment by MadLittleMods** [comment]
I added support for block helpers:
`{{#@helpers/include.helper title="Lobby" url="http://google.com/" }}{{> ./tiny-link.partial }}{{/helpers/include.helper}}`

Also updated the test with an example.

**Comment by guybedford** [comment]
This is really great, but we do need to maintain the build stuff!

What is your use case that you can afford to load a full parser in production? I would strongly advise looking into the builds, they're not as complex as they sound at all.

**Comment by MadLittleMods** [comment]
It is very unique use case where everything is local (Game GUI). So the performance hit of waiting for separate things to load is not a huge deal. Of course a build will probably make it perform better but I haven't hit that wall.

The block helper code, I think, could be combined into a single regex to improve performance but I just needed that feature and slapped it in.

I get the general concept of the build but it is bit hazy on how I need to implement it to get it right.

As a note, the code does match partials that you may have in a multi-line comment. I did originally use the parser to ignore stuff in comments like the more popular handlebars require plugin. But I decided to just go the regex route as that is what you were already doing and just wanted to conform.

**Comment by guybedford** [comment]
Ah ok. Yeah it just has to spit out the right source, with the right form of the dependencies and everything.

I just don't have time to properly test all this, but I really like your work, and you haven't overwritten what was there before.

For now I'm just going to accept this, and continue on the assumption that this project is entirely in development and not supported at all!

**Pull request merged**
